platform :ios, '8.1'
use_frameworks!

pod 'SWRevealViewController'
pod 'GoogleMaps'
pod 'Charts', '2.2.2'
pod 'Bolts'
pod 'FBSDKCoreKit'
pod 'FBSDKShareKit'
pod 'FBSDKLoginKit'
pod 'Alamofire', '3.2.1'
